// <auto-generated />
namespace TakipProje.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class YenilikEklendi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(YenilikEklendi));
        
        string IMigrationMetadata.Id
        {
            get { return "202306141144352_YenilikEklendi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
